AppBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        parentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: parent_id
    lifecycleCallbacks: {  }
