AppBundle\Entity\Order:
    type: entity
    table: order
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        address:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
        deliveryTime:
            type: datetime
            nullable: false
            column: delivery_time
        total:
            type: integer
            nullable: false
            options:
                unsigned: false
        firstName:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: last_name
        phone:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        deliveryType:
            type: boolean
            nullable: false
            column: delivery_type
        paymentType:
            type: boolean
            nullable: false
            column: payment_type
        shortChange:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: short_change
        note:
            type: string
            nullable: false
            length: 16000
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
