AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        contains:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
        price:
            type: integer
            nullable: false
            options:
                unsigned: false
        priceOld:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: price_old
        weight:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
        stickerTop:
            type: smallint
            nullable: false
            options:
                unsigned: false
            column: sticker_top
        stickerBottom:
            type: smallint
            nullable: false
            options:
                unsigned: false
            column: sticker_bottom
        recommended:
            type: integer
            nullable: false
            options:
                unsigned: false
        categoryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: category_id
    lifecycleCallbacks: {  }
